// Official DKU course catalog extracted from the 2025-2026 Undergraduate
// Bulletin, used to power the "search the catalog" picker on Add Course so
// most adds are select-and-done. Cross-listed courses (e.g. "COMPSCI 206 /
// ECON 206") appear once per subject they're listed under, since students
// register under a specific code. A course not in here can still be added by
// hand. Regenerate from a newer bulletin rather than hand-editing.
export type CatalogCourse = {
  code: string;
  title: string;
  department: string;
  credits: string;
  crossListed: string[];
};

export const DKU_COURSE_CATALOG: CatalogCourse[] = [
  { code: "ARTS 21", title: "General Art, Studio", department: "Arts", credits: "4", crossListed: [] },
  { code: "ARTS 105", title: "The Science of Traditional Asian Music", department: "Arts", credits: "4", crossListed: ["PHYS 105"] },
  { code: "ARTS 106", title: "European Art History 1", department: "Arts", credits: "4", crossListed: ["HIST 106"] },
  { code: "ARTS 107", title: "Around the World with Seven Masterpieces", department: "Arts", credits: "2", crossListed: [] },
  { code: "ARTS 201", title: "Introduction to Film Studies", department: "Arts", credits: "4", crossListed: [] },
  { code: "ARTS 202", title: "Contemporary Documentary Film", department: "Arts", credits: "4", crossListed: [] },
  { code: "ARTS 203", title: "Visual China: Modern Chinese History and Culture Through Film", department: "Arts", credits: "4", crossListed: ["GCHINA 203"] },
  { code: "ARTS207", title: "History of Art and Science", department: "Arts", credits: "4", crossListed: ["HIST 207"] },
  { code: "ARTS 208", title: "From Cool Japan to the Korean Wave: Popular Culture from East Asia", department: "Arts", credits: "4", crossListed: ["LIT 208"] },
  { code: "ARTS 210", title: "Global Art History", department: "Arts", credits: "4", crossListed: ["HIST 210"] },
  { code: "ARTS 217", title: "Arts of China", department: "Arts", credits: "4", crossListed: ["HIST 217"] },
  { code: "ARTS 218", title: "Women in East Asian Art", department: "Arts", credits: "4", crossListed: ["HIST 218"] },
  { code: "ARHU 101", title: "The Art of Interpretation: Written Texts", department: "Arts and Humanities", credits: "4", crossListed: [] },
  { code: "ARHU 102", title: "The Art of Interpretation: Images and Sound", department: "Arts and Humanities", credits: "4", crossListed: [] },
  { code: "BEHAVSCI 101", title: "Introduction to Behavioral Science", department: "Behavior Science", credits: "4", crossListed: [] },
  { code: "BEHAVSCI 102", title: "Mechanisms of Human Behavior", department: "Behavior Science", credits: "4", crossListed: [] },
  { code: "BEHAVSCI 201", title: "Individuals and Their Decisions", department: "Behavior Science", credits: "4", crossListed: [] },
  { code: "BEHAVSCI 202", title: "Institutions, Groups, and Society", department: "Behavior Science", credits: "4", crossListed: [] },
  { code: "BEHAVSCI 203", title: "Comparative Analysis of Behavior", department: "Behavior Science", credits: "4", crossListed: [] },
  { code: "BEHAVSCI 204", title: "Experimental Philosophy", department: "Behavior Science", credits: "4", crossListed: [] },
  { code: "BEHAVSCI 205", title: "Systems and Circuits", department: "Behavior Science", credits: "4", crossListed: [] },
  { code: "BEHAVSCI 301", title: "Computational Neuroscience", department: "Behavior Science", credits: "4", crossListed: [] },
  { code: "BEHAVSCI 303", title: "Organizational Behavior and Leadership", department: "Behavior Science", credits: "4", crossListed: ["ETHLDR 303"] },
  { code: "BEHAVSCI 401", title: "Moving Beyond Nudges", department: "Behavior Science", credits: "4", crossListed: [] },
  { code: "BEHAVSCI 402", title: "Judgement and Decision Making", department: "Behavior Science", credits: "4", crossListed: [] },
  { code: "BIOL 20", title: "General Biology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 102", title: "Introduction to Human Biology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 110", title: "Integrated Science -- Biology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 111", title: "Introduction to Human Anatomy and Physiology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 201", title: "Cell and Molecular Biology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 202", title: "Genetics and Evolution", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 203", title: "Molecular, Behavioral and Social Evolution: Darwin's Theories between Science and Culture", department: "Biology", credits: "4", crossListed: ["GCULS 203"] },
  { code: "BIOL 208", title: "General Ecology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 212", title: "Microbiology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 304", title: "Molecular Genetic Analysis", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 305", title: "Biochemistry", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 306", title: "Cell Signaling and Diseases", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 307", title: "Cancer Genetics", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 308", title: "Evolution of Infectious Diseases", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 310", title: "Developmental Biology: Development, Stem Cells, and Regeneration", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 311", title: "Biogeochemistry", department: "Biology", credits: "4", crossListed: ["ENVIR 311"] },
  { code: "BIOL 312", title: "Ecophysiology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 313", title: "Ecosystem Service", department: "Biology", credits: "4", crossListed: ["ENVIR 313"] },
  { code: "BIOL 314", title: "Computational Biology and Bioinformatics", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 315", title: "Experimental Molecular Biology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 316", title: "Quantitative Physiology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 317", title: "Systems Biology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 318", title: "Food Web Ecology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 319", title: "Global Change Biology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 320", title: "Bioethics", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 321", title: "Advanced Topics in Cellular and Molecular Biology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 323", title: "Plant Environmental Stress Biology", department: "Biology", credits: "4", crossListed: ["ENVIR 323"] },
  { code: "BIOL 401", title: "Advanced Biochemistry: Cell Metabolism", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 403", title: "Experimental Methods in Functional Genomics", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 404", title: "Genomics of Adaptation", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 405", title: "Microbial Ecology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 406", title: "Population Ecology", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 407", title: "Population Genomics and Molecular Evolution", department: "Biology", credits: "4", crossListed: [] },
  { code: "BIOL 408", title: "Pharmacology: Science and Society", department: "Biology", credits: "4", crossListed: ["CHEM 408", "GLHLTH 408"] },
  { code: "BIOL 409", title: "Fundamental Immunology", department: "Biology", credits: "4", crossListed: ["GLHLTH 409"] },
  { code: "BIOL 410", title: "Principles of Nutrition and Disease", department: "Biology", credits: "4", crossListed: ["GLHLTH 410"] },
  { code: "BIOL 411", title: "Vaccine Development for Emerging Infectious Diseases", department: "Biology", credits: "4", crossListed: ["GLHLTH 411"] },
  { code: "BIOL 412", title: "Principles of Medicinal Chemistry", department: "Biology", credits: "4", crossListed: ["CHEM412", "GLHLTH 412"] },
  { code: "CAPSTONE 495", title: "Signature Work Capstone I", department: "Capstone", credits: "2-4", crossListed: [] },
  { code: "CAPSTONE 496", title: "Signature Work Capstone II", department: "Capstone", credits: "4", crossListed: [] },
  { code: "CHEM 20", title: "General Chemistry", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM 105", title: "Chemistry in Context", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM 110", title: "Integrated Science -- Chemistry", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM 150", title: "General Chemistry II", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM 201", title: "Organic Chemistry I", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM 202", title: "Organic Chemistry II", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM 205", title: "Quantitative Chemical Analysis", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM 301", title: "Elements of Physical Chemistry", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM 315", title: "Aqueous Geochemistry", department: "Chemistry", credits: "4", crossListed: ["ENVIR 315"] },
  { code: "CHEM 401", title: "Analytical Chemistry", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM 402", title: "Inorganic Chemistry", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM 403", title: "Advanced Topics in Physical Chemistry", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM 404", title: "Physical Biochemistry", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM 408", title: "Pharmacology: Science and Society", department: "Chemistry", credits: "4", crossListed: ["BIOL 408", "GLHLTH 408"] },
  { code: "CHEM 410", title: "Advanced Materials Chemistry Laboratory (Lab)", department: "Chemistry", credits: "4", crossListed: [] },
  { code: "CHEM412", title: "Principles of Medicinal Chemistry", department: "Chemistry", credits: "4", crossListed: ["BIOL 412", "GLHLTH 412"] },
  { code: "CHINESE 101A", title: "Beginning Chinese 1 -- A", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 101B", title: "Beginning Chinese 1 -- B", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 102A", title: "Beginning Chinese 2 -- A", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 131A", title: "First Year Chinese for Heritage Learners 1 -- A", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 131B", title: "First Year Chinese for Heritage Learners 1 -- B", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 132A", title: "First Year Chinese for Heritage Learners 2 -- A", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 132B", title: "First Year Chinese for Heritage Learners 2 -- B", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 201A", title: "Intermediate Chinese 1 -- A", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 202A", title: "Intermediate Chinese 2 -- A", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 231A", title: "Second Year Chinese for Heritage Learners 1 -- A", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 231B", title: "Second Year Chinese for Heritage Learners 1 -- B", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 232A", title: "Second Year Chinese for Heritage Learners 2 -- A", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 232B", title: "Second Year Chinese for Heritage Learners 2 -- B", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 301A", title: "Advanced Intermediate Chinese 1 -- A", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 301B", title: "Advanced Intermediate Chinese 1 -- B", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 302A", title: "Advanced Intermediate Chinese 2 -- A", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 302B", title: "Advanced Intermediate Chinese 2 -- B", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 401A", title: "Advanced Chinese -- Issues in Modern China 1 -- A", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 401B", title: "Advanced Chinese -- Issues in Modern China 1 -- B", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 402A", title: "Advanced Chinese -- Issues in Modern China 2 -- A", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 402B", title: "Advanced Chinese -- Issues in Modern China 2 -- B", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 403", title: "Readings in Pre-Modern Chinese", department: "Chinese", credits: "4", crossListed: [] },
  { code: "CHINESE 404", title: "Readings in Modern Chinese Fiction", department: "Chinese", credits: "4", crossListed: [] },
  { code: "CHINESE 405", title: "Readings in Contemporary Chinese Fiction", department: "Chinese", credits: "4", crossListed: [] },
  { code: "CHINESE 406A", title: "Debating Issues in Contemporary China -- A", department: "Chinese", credits: "4", crossListed: [] },
  { code: "CHINESE 406B", title: "Debating Issues in Contemporary China -- B", department: "Chinese", credits: "4", crossListed: [] },
  { code: "CHINESE 407", title: "Readings in Classical Chinese", department: "Chinese", credits: "4", crossListed: [] },
  { code: "CHINESE 408", title: "Translation Workshop: The Reflection of Meaning", department: "Chinese", credits: "2", crossListed: ["WOC 207"] },
  { code: "CHINESE 409", title: "Chinese Book Club", department: "Chinese", credits: "4", crossListed: [] },
  { code: "CHINESE 410A", title: "Public Speaking in Chinese", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 410B", title: "Public Speaking in Chinese", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 411", title: "Professional Networking in China", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 412", title: "Chinese Across the Curriculum: Independent Research", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 413", title: "Advanced Chinese -- New Media Narratives", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 414", title: "Reading Chinese Love Stories in Novels and Memoirs", department: "Chinese", credits: "2", crossListed: ["WOC 214"] },
  { code: "CHINESE 415", title: "Watching Forbidden Love in Chinese Films", department: "Chinese", credits: "2", crossListed: ["WOC 215"] },
  { code: "CHINESE 416", title: "Translation Workshop: Adaptation and Transformation (Chinese-English; English-Chinese)", department: "Chinese", credits: "2", crossListed: ["WOC 210"] },
  { code: "CHINESE 418", title: "Business Chinese: Plan a Business in China", department: "Chinese", credits: "2", crossListed: [] },
  { code: "CHINESE 419", title: "Travelling Texts, Moving Images: East Meets West in Film Remakes", department: "Chinese", credits: "2", crossListed: ["WOC 219"] },
  { code: "CHINESE 422", title: "Martial Arts Cinema: Nation, Gender, and Identity", department: "Chinese", credits: "2", crossListed: ["WOC 222"] },
  { code: "CHINESE 423", title: "Topics in Modern and Premodern Chinese Literature", department: "Chinese", credits: "4", crossListed: ["LIT 223"] },
  { code: "CHINESE 491", title: "Independent Study in Chinese", department: "Chinese", credits: "4", crossListed: [] },
  { code: "CHSC 101", title: "Chinese Humanistic Spirit and Institutions", department: "Chinese Society and Culture", credits: "6", crossListed: [] },
  { code: "CHSC 102", title: "Social Changes in China", department: "Chinese Society and Culture", credits: "6", crossListed: [] },
  { code: "CHSC 103", title: "Selected Readings of Chinese Classics", department: "Chinese Society and Culture", credits: "2", crossListed: [] },
  { code: "CHSC 104", title: "Trends and Policies", department: "Chinese Society and Culture", credits: "2", crossListed: [] },
  { code: "CHSC 105", title: "An Introduction to the Basic Principles of Marxism", department: "Chinese Society and Culture", credits: "2", crossListed: [] },
  { code: "CHSC 106", title: "Appreciation of World Chinese Literature Classics", department: "Chinese Society and Culture", credits: "2", crossListed: [] },
  { code: "CHSC 107", title: "An Introduction to Chinese Culture", department: "Chinese Society and Culture", credits: "2", crossListed: [] },
  { code: "COMPDSGN 490", title: "Senior Seminar", department: "Computer Design", credits: "4", crossListed: [] },
  { code: "COMPSCI 20", title: "Computer Science Principles", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 101", title: "Introduction to Computer Science", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 201", title: "Introduction to Programming and Data Structures", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 203", title: "Discrete Math for Computer Science", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 204", title: "Introduction to Artificial Intelligence", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 205", title: "Computer Organization and Programming", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 206", title: "Computational Microeconomics", department: "Computer Science", credits: "4", crossListed: ["ECON 206"] },
  { code: "COMPSCI 207", title: "Image Data Science", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 208", title: "Computer Graphics", department: "Computer Science", credits: "4", crossListed: ["MEDIART 206"] },
  { code: "COMPSCI 210", title: "Everything Data", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 301", title: "Algorithms and Databases", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 302", title: "Computer Vision", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 303", title: "Search Engines", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 304", title: "Speech Recognition", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 306", title: "Introduction to Operating Systems", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 307", title: "Software Design and Implementation", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 308", title: "Design and Analysis of Algorithms", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 309", title: "Principles of Machine Learning", department: "Computer Science", credits: "4", crossListed: ["STATS 302"] },
  { code: "COMPSCI 310", title: "Introduction to Databases", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 311", title: "Computer Network Architecture", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 320", title: "Software Reliability", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 401", title: "Cloud Computing", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 402", title: "Artificial Intelligence", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 403", title: "Programming Languages and Compilers", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 404", title: "Computer Architecture and Hardware Design", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 405", title: "Embedded Systems", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "COMPSCI 406", title: "Logic and Formal Methods", department: "Computer Science", credits: "4", crossListed: [] },
  { code: "CULANTH 20", title: "Topics in Cultural Anthropology Studies", department: "Cultural Anthropology", credits: "4", crossListed: [] },
  { code: "CULANTH 101", title: "Introduction to Cultural Anthropology", department: "Cultural Anthropology", credits: "4", crossListed: [] },
  { code: "CULANTH 106", title: "Home, House, and Housing: An Anthropological Exploration of Human Dwellings", department: "Cultural Anthropology", credits: "2", crossListed: [] },
  { code: "CULANTH 107", title: "Food, Ethnicity and Globalization", department: "Cultural Anthropology", credits: "2", crossListed: [] },
  { code: "CULANTH 201", title: "New Media and Society", department: "Cultural Anthropology", credits: "4", crossListed: ["MEDIA 201"] },
  { code: "CULANTH 202", title: "Culture and Industry", department: "Cultural Anthropology", credits: "4", crossListed: ["GCULS 201", "MEDIA 202"] },
  { code: "CULANTH 206", title: "China Stories: Local Cultures and Communities", department: "Cultural Anthropology", credits: "4", crossListed: [] },
  { code: "CULANTH 207", title: "Cultures of New Media", department: "Cultural Anthropology", credits: "4", crossListed: ["MEDIA 207"] },
  { code: "CULANTH 208", title: "Global Migration and Ethics", department: "Cultural Anthropology", credits: "4", crossListed: [] },
  { code: "CULANTH 210", title: "Ethnographic Field Methods", department: "Cultural Anthropology", credits: "4", crossListed: [] },
  { code: "CULANTH 211", title: "Race, Gender, and Labor in the City", department: "Cultural Anthropology", credits: "4", crossListed: [] },
  { code: "CULANTH 213", title: "Globalization, Sustainability, and Technology", department: "Cultural Anthropology", credits: "4", crossListed: [] },
  { code: "CULANTH 214", title: "Cultures of Fascism", department: "Cultural Anthropology", credits: "4", crossListed: [] },
  { code: "CULANTH 220", title: "Visual Anthropology", department: "Cultural Anthropology", credits: "4", crossListed: ["MEDIART 220"] },
  { code: "CULANTH 303", title: "Politics of Food: Land, Labor, Health, and Economics", department: "Cultural Anthropology", credits: "4", crossListed: [] },
  { code: "CULANTH 304", title: "Rethinking Progress: Capitalism, Development, and its Alternatives", department: "Cultural Anthropology", credits: "4", crossListed: [] },
  { code: "CULANTH 305", title: "The Culture of Development: Africa", department: "Cultural Anthropology", credits: "4", crossListed: [] },
  { code: "CULANTH 314", title: "Migration, the State, and Refugees", department: "Cultural Anthropology", credits: "4", crossListed: ["POLSCI 314"] },
  { code: "CULANTH 405", title: "Bodies, Medicine, Healing", department: "Cultural Anthropology", credits: "4", crossListed: [] },
  { code: "CULMOVE 201", title: "Migration, Inequality and Culture", department: "Cultures and Movements", credits: "4", crossListed: [] },
  { code: "CULMOVE 203", title: "Wealth, Inequality and Power", department: "Cultures and Movements", credits: "4", crossListed: [] },
  { code: "CULMOVE 206", title: "Ethnic and Religious Diversity in the Middle East", department: "Cultures and Movements", credits: "4", crossListed: [] },
  { code: "CULMOVE 301", title: "Social Science Perspectives on China: From the Socialist Past to the Global Present", department: "Cultures and Movements", credits: "4", crossListed: [] },
  { code: "CULMOVE 302", title: "Culture and Social Movements", department: "Cultures and Movements", credits: "4", crossListed: [] },
  { code: "CULMOVE 390", title: "Junior Seminar: Advanced Topics", department: "Cultures and Movements", credits: "4", crossListed: [] },
  { code: "CULMOVE 490", title: "Senior Seminar: Advanced Topics", department: "Cultures and Movements", credits: "4", crossListed: [] },
  { code: "CULSOC 101", title: "Cultures and Societies", department: "Cultures and Societies", credits: "4", crossListed: [] },
  { code: "CULSOC 201", title: "Social Inequalities", department: "Cultures and Societies", credits: "4", crossListed: [] },
  { code: "CULSOC 205", title: "Religion, Power, and Social Change", department: "Cultures and Societies", credits: "4", crossListed: ["RELIG 205"] },
  { code: "CULSOC 301", title: "Theories of Social Change", department: "Cultures and Societies", credits: "4", crossListed: [] },
  { code: "CULSOC 390", title: "Junior Seminar: Advanced Topics", department: "Cultures and Societies", credits: "4", crossListed: [] },
  { code: "CULSOC 490", title: "Senior Seminar: Advanced Topics", department: "Cultures and Societies", credits: "4", crossListed: [] },
  { code: "DKU 102", title: "Talking Climate Change", department: "DKU", credits: "2", crossListed: [] },
  { code: "ECON 21", title: "Introduction to Microeconomics", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 22", title: "Introduction to Macroeconomics", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 101", title: "Economics Principles", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 201", title: "Intermediate Microeconomics I", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 202", title: "Intermediate Microeconomics II", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 204", title: "Intermediate Macroeconomics", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 206", title: "Computational Microeconomics", department: "Economics", credits: "4", crossListed: ["COMPSCI 206"] },
  { code: "ECON 207", title: "Survey of Economic Policy", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 211", title: "Intelligent Economics: An Explainable AI approach", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 212", title: "Comparative Economic History", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 213", title: "Sustainable Investing", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 225", title: "History of Economic Thought", department: "Economics", credits: "4", crossListed: ["HIST 225"] },
  { code: "ECON 301", title: "Health Economics", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 302", title: "Environmental Economics & Policy", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 303", title: "Financial Institutions", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 304", title: "Economic Growth", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 305", title: "Mathematical Economics", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 307", title: "History of Monetary & International Crises", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 309", title: "Behavioral Finance", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 310", title: "Urban Economics", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 314", title: "International Trade", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 315", title: "Economics of the Public Sector", department: "Economics", credits: "4", crossListed: ["PUBPOL 315"] },
  { code: "ECON 317", title: "Quantitative Finance", department: "Economics", credits: "4", crossListed: ["MATH 317"] },
  { code: "ECON 318", title: "Game Theory", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 333", title: "Social and Economic Networks", department: "Economics", credits: "4", crossListed: ["SOSC 333"] },
  { code: "ECON 401", title: "Competitive Strategy and Industrial Organization", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 402", title: "International Finance", department: "Economics", credits: "4", crossListed: [] },
  { code: "ECON 404", title: "Environmental Justice: The Economics of Race, Place and Pollution", department: "Economics", credits: "4", crossListed: ["ENVIR 404"] },
  { code: "ECON 411", title: "Stochastic Process for Finance", department: "Economics", credits: "4", crossListed: ["MATH 411"] },
  { code: "ENGLISH 20", title: "Literature and Composition", department: "English", credits: "4", crossListed: [] },
  { code: "ENGLISH 22", title: "Composition and Language", department: "English", credits: "4", crossListed: [] },
  { code: "EAP 101A", title: "Writing about Language Learning -- A", department: "English for Academic Purposes", credits: "2", crossListed: [] },
  { code: "EAP 101B", title: "Writing about Language Learning -- B", department: "English for Academic Purposes", credits: "2", crossListed: [] },
  { code: "EAP 102A", title: "Writing about Culture Learning -- A", department: "English for Academic Purposes", credits: "2", crossListed: [] },
  { code: "EAP 102B", title: "Writing about Culture Learning -- B", department: "English for Academic Purposes", credits: "2", crossListed: [] },
  { code: "EAP 103", title: "Writing about Intercultural Encounters", department: "English for Academic Purposes", credits: "2", crossListed: [] },
  { code: "EAP 110", title: "Presenting Ideas to Global Audiences", department: "English for Academic Purposes", credits: "2", crossListed: [] },
  { code: "EAP 201", title: "Building Intercultural Competence", department: "English for Academic Purposes", credits: "4", crossListed: [] },
  { code: "EAP 202", title: "Studying Cultures through the Media", department: "English for Academic Purposes", credits: "4", crossListed: [] },
  { code: "EAP 203", title: "Global Languages", department: "English for Academic Purposes", credits: "4", crossListed: [] },
  { code: "EAP 204", title: "Endangered Languages", department: "English for Academic Purposes", credits: "4", crossListed: [] },
  { code: "EAP 205", title: "Strategies for Independent Language Learning", department: "English for Academic Purposes", credits: "4", crossListed: [] },
  { code: "ENVIR 20", title: "Environmental Science", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 101", title: "Introduction to Environmental Sciences", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 102", title: "Dynamic Earth and Oceans: Physical and Biological Sciences for the Environment", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 201", title: "Applied Environmental Science and Policy", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 202", title: "Biodiversity and Conservation", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 203", title: "The Theory and Practice of Sustainability", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 204", title: "Global Environmental Issues and Policies", department: "Environment", credits: "2", crossListed: [] },
  { code: "ENVIR 206", title: "Energy and the Environment", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 208", title: "Environmental Data Analytics", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 301", title: "International Environmental Policy", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 302", title: "Environmental Economics & Policy", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 303", title: "Climate Change and Society in China", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 304", title: "Environmental Chemistry and Toxicology", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 305", title: "Environment and Development Economics in Developing Countries", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 306", title: "Water Pollution", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 308", title: "Life Cycle Assessment", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 310", title: "Elements of Physical Hydrology", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 311", title: "Biogeochemistry", department: "Environment", credits: "4", crossListed: ["BIOL 311"] },
  { code: "ENVIR 313", title: "Ecosystem Service", department: "Environment", credits: "4", crossListed: ["BIOL 313"] },
  { code: "ENVIR 315", title: "Aqueous Geochemistry", department: "Environment", credits: "4", crossListed: ["CHEM 315"] },
  { code: "ENVIR 323", title: "Plant Environmental Stress Biology", department: "Environment", credits: "4", crossListed: ["BIOL 323"] },
  { code: "ENVIR 401", title: "Energy and Environment Design", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 402", title: "Chemical Transformation of Environmental Contaminants", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 403", title: "Energy Economics and Policy", department: "Environment", credits: "4", crossListed: [] },
  { code: "ENVIR 404", title: "Environmental Justice: The Economics of Race, Place and Pollution", department: "Environment", credits: "4", crossListed: ["ECON 404"] },
  { code: "ETHLDR 101", title: "Ethics and Leadership", department: "Ethics and Leadership", credits: "4", crossListed: [] },
  { code: "ETHLDR 108", title: "Democracy and Inclusion: Hopes, Prospects, Dilemmas", department: "Ethics and Leadership", credits: "2", crossListed: [] },
  { code: "ETHLDR 201", title: "Ethics, Citizenship and the Examined Life", department: "Ethics and Leadership", credits: "4", crossListed: [] },
  { code: "ETHLDR 204", title: "Environmental Ethics", department: "Ethics and Leadership", credits: "4", crossListed: [] },
  { code: "ETHLDR 205", title: "Trust and Cross-Cultural Leadership", department: "Ethics and Leadership", credits: "4", crossListed: [] },
  { code: "ETHLDR 206", title: "Global Justice and Health Care", department: "Ethics and Leadership", credits: "4", crossListed: [] },
  { code: "ETHLDR 209", title: "The Psychology of Values", department: "Ethics and Leadership", credits: "4", crossListed: [] },
  { code: "ETHLDR 210", title: "The Sociology of Morality and Politics", department: "Ethics and Leadership", credits: "4", crossListed: [] },
  { code: "ETHLDR 301", title: "Ethics of Nudging", department: "Ethics and Leadership", credits: "4", crossListed: [] },
  { code: "ETHLDR 303", title: "Organizational Behavior and Leadership", department: "Ethics and Leadership", credits: "4", crossListed: ["BEHAVSCI 303"] },
  { code: "FRENCH 101", title: "Beginning French 101", department: "French", credits: "4", crossListed: [] },
  { code: "FRENCH 102", title: "Beginning French 2", department: "French", credits: "4", crossListed: [] },
  { code: "GERMAN 24", title: "Advanced Placement in German", department: "German", credits: "4", crossListed: [] },
  { code: "GERMAN 101", title: "Beginning German 1", department: "German", credits: "4", crossListed: [] },
  { code: "GERMAN 102", title: "Beginning German 2", department: "German", credits: "4", crossListed: [] },
  { code: "GCHINA101", title: "China in the World", department: "Global China Studies", credits: "4", crossListed: [] },
  { code: "GCHINA 108", title: "Exploring China: Introduction to the Jiangnan Region", department: "Global China Studies", credits: "4", crossListed: [] },
  { code: "GCHINA 201", title: "From Empire to Nation", department: "Global China Studies", credits: "4", crossListed: [] },
  { code: "GCHINA 202", title: "Modern Chinese Politics", department: "Global China Studies", credits: "4", crossListed: [] },
  { code: "GCHINA 203", title: "Visual China: Modern Chinese History and Culture through Film", department: "Global China Studies", credits: "4", crossListed: ["ARTS 203"] },
  { code: "GCHINA 204", title: "Politics of Art and Art of Politics in China", department: "Global China Studies", credits: "4", crossListed: [] },
  { code: "GCHINA 205", title: "Ideas Across Borders: China's Intellectual Engagement with the World", department: "Global China Studies", credits: "4", crossListed: [] },
  { code: "GCHINA 206", title: "History of Suzhou", department: "Global China Studies", credits: "4", crossListed: [] },
  { code: "GCHINA 301", title: "China's Economic Transition", department: "Global China Studies", credits: "4", crossListed: ["POLECON 302"] },
  { code: "GCHINA 302", title: "The Factory: From Socialist Industrialism to World Assembly", department: "Global China Studies", credits: "4", crossListed: [] },
  { code: "GCHINA 304", title: "US/China Relations", department: "Global China Studies", credits: "4", crossListed: [] },
  { code: "GCHINA 305", title: "Family and Society in China", department: "Global China Studies", credits: "4", crossListed: [] },
  { code: "GCHINA 390", title: "Junior Seminar: Advanced Topics", department: "Global China Studies", credits: "4", crossListed: [] },
  { code: "GCHINA 401", title: "Political Economy of the Chinese Reform", department: "Global China Studies", credits: "4", crossListed: ["POLECON 401"] },
  { code: "GCHINA 490", title: "Senior Seminar: China's Turning Points", department: "Global China Studies", credits: "4", crossListed: [] },
  { code: "GCULS 106", title: "Our Cities and Ourselves", department: "Global Cultural Studies", credits: "2", crossListed: [] },
  { code: "GCULS 107", title: "Berlin-Paris: Sex, Cigarettes, and the Meaning of Life", department: "Global Cultural Studies", credits: "2", crossListed: [] },
  { code: "GCULS 108", title: "Science, Culture, and Politics", department: "Global Cultural Studies", credits: "2", crossListed: [] },
  { code: "GCULS 119", title: "Fashion and Gender in China", department: "Global Cultural Studies", credits: "2", crossListed: ["MEDIART 119"] },
  { code: "GCULS 201", title: "Culture and Industry", department: "Global Cultural Studies", credits: "4", crossListed: ["CULANTH 202", "MEDIA 202"] },
  { code: "GCULS 226", title: "Eco-Cinema: China's Environmental and Ecological Crisis", department: "Global Cultural Studies", credits: "4", crossListed: ["MEDIART 226"] },
  { code: "GCULS 301", title: "Religion and Sexuality", department: "Global Cultural Studies", credits: "4", crossListed: [] },
  { code: "GCULS 303", title: "Chinatowns: A Cultural History", department: "Global Cultural Studies", credits: "4", crossListed: [] },
  { code: "GCULS 304", title: "Chinese Culture and Ideology in the 20th Century and Now", department: "Global Cultural Studies", credits: "4", crossListed: [] },
  { code: "GCULS 390", title: "Junior Seminar: Advanced Topics", department: "Global Cultural Studies", credits: "4", crossListed: [] },
  { code: "GCULS 401", title: "Games and Culture: Politics, Pleasure and Pedagogy", department: "Global Cultural Studies", credits: "4", crossListed: [] },
  { code: "GLHLTH 101", title: "Introduction to Global Health", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 105", title: "Novel Coronavirus: Epidemics and Response in the Age of Global Interdependence", department: "Global Health", credits: "2", crossListed: [] },
  { code: "GLHLTH 201", title: "Global Health Ethics", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 202", title: "Media and Health Communication", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 205", title: "Social Determinants of Health", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 280", title: "Ecosystem Health and Human Well-Being", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 301", title: "Global Health Research Methods", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 303", title: "Global Comparative Health Care Systems", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 304", title: "Global Health Governance and Policy", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 305", title: "Biological Basis of Disease", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 306", title: "Evolution of Health and Disease", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 307", title: "[Global Mental Health](https://globalhealth.duke.edu/education-and-training/undergraduate/courses)", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 310", title: "Global Disease Control Programs and Policies", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 311", title: "Introduction to Epidemiology", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 312", title: "Global Aging and Care", department: "Global Health", credits: "4", crossListed: [] },
  { code: "GLHLTH 409", title: "Fundamental Immunology", department: "Global Health", credits: "4", crossListed: ["BIOL 409"] },
  { code: "GLHLTH 410", title: "Principles of Nutrition and Disease", department: "Global Health", credits: "4", crossListed: ["BIOL 410"] },
  { code: "GLHLTH 411", title: "Vaccine Development for Emerging Infectious Diseases", department: "Global Health", credits: "4", crossListed: ["BIOL 411"] },
  { code: "GLHLTH 412", title: "Principles of Medicinal Chemistry", department: "Global Health", credits: "4", crossListed: ["CHEM412", "BIOL 412"] },
  { code: "HIST 20", title: "Basic Art History", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 21", title: "World History", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 23", title: "American History I", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 24", title: "American History II", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 25", title: "European History I", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 26", title: "European History II", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 102", title: "Medieval Chinese History", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 103", title: "Premodern Chinese History", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 104", title: "American History to 1876", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 105", title: "American History from Reconstruction to the Present", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 106", title: "European Art History 1", department: "History", credits: "4", crossListed: ["ARTS 106"] },
  { code: "HIST 108", title: "Shanghai Nightscapes: A Nocturnal History of the City", department: "History", credits: "2", crossListed: [] },
  { code: "HIST 110", title: "Historical Perspectives on Contemporary Global Issues", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 111", title: "Ancient Roots to Global Routes", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 114", title: "Conflicts and Resolutions Modern South Asia", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 115", title: "Brides of the Sea: Trading Cities in the Indian Ocean World, 200BCE to 2000CE", department: "History", credits: "2", crossListed: [] },
  { code: "HIST 116", title: "Mughal India Travel Writing", department: "History", credits: "2", crossListed: [] },
  { code: "HIST 117", title: "Sounds and the Chinese City: Live Music Scenes in Urban China", department: "History", credits: "2", crossListed: [] },
  { code: "HIST 118", title: "The American Empire", department: "History", credits: "2", crossListed: [] },
  { code: "HIST 119", title: "The Birth of the Modern Middle East: 1918-1930", department: "History", credits: "2", crossListed: [] },
  { code: "HIST 121", title: "Pan-Africanism: Global Story of an Idea", department: "History", credits: "2", crossListed: [] },
  { code: "HIST 122", title: "World History in Seven Meals", department: "History", credits: "2", crossListed: [] },
  { code: "HIST 123", title: "All Around Us -- Technology, Infrastructure, and History", department: "History", credits: "2", crossListed: [] },
  { code: "HIST 124", title: "Outcast: Refugees, Memory, and the Borders of Belonging", department: "History", credits: "2", crossListed: [] },
  { code: "HIST 201", title: "Methods of Historical Research", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 202", title: "Global Interactions in Historical Perspective", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 204", title: "Asia in World History", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 205", title: "Shanghai: From Treaty Port to Global Metropolis", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 207", title: "History of Art and Science", department: "History", credits: "4", crossListed: ["ARTS 207"] },
  { code: "HIST 208", title: "America Fractured", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 209", title: "Refugees and War since 1914", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 210", title: "Global Art History", department: "History", credits: "4", crossListed: ["ARTS 210"] },
  { code: "HIST 212", title: "Pandemics in World History from the Black Death to COVID-19", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 217", title: "Arts of China", department: "History", credits: "4", crossListed: ["ARTS 217"] },
  { code: "HIST 218", title: "Women in East Asian Art", department: "History", credits: "4", crossListed: ["ARTS 218"] },
  { code: "HIST 219", title: "The History of the Modern Middle East: 1930-1990", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 220", title: "Global Media History", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 223", title: "Global Histories of Risk and Disaster", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 224", title: "Histories of Gender", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 225", title: "History of Economic Thought", department: "History", credits: "4", crossListed: ["ECON 225"] },
  { code: "HIST 226", title: "History of Chinese Philosophy", department: "History", credits: "4", crossListed: ["PHIL 226"] },
  { code: "HIST 228", title: "Power, Technology, and the Environment", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 229", title: "Labor, Migration, and the Making of the Modern World", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 230", title: "The History of Everyday Life", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 250", title: "Gandhi and Moral Leadership", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 301", title: "China and the Silk Roads World: 500-1500", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 302", title: "China in Global Perspective 2: The Internationalization of Modern China", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 306", title: "The United States and China in War and Revolution", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 309", title: "Global Commodities and Their Discontents", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 314", title: "Writing the History of War", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 316", title: "The Modern Regulatory State", department: "History", credits: "4", crossListed: ["PUBPOL 316"] },
  { code: "HIST 317", title: "The Global First World War", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 318", title: "World History and Asia", department: "History", credits: "4", crossListed: [] },
  { code: "HIST401", title: "Global Connections", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 410", title: "The Spice Race: How the Spice Trade shaped our World", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 412", title: "Global Labor History", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 413", title: "The Color Line: A Worldwide History of White Supremacy", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 414", title: "The Age of Revolutions, 1640-1865", department: "History", credits: "4", crossListed: [] },
  { code: "HIST 415", title: "The Origins of Capitalism, 1500-1900", department: "History", credits: "4", crossListed: [] },
  { code: "HUM 105", title: "Critical Comparative Studies", department: "Humanities", credits: "4", crossListed: [] },
  { code: "HUM 202", title: "Empires and Culture", department: "Humanities", credits: "4", crossListed: [] },
  { code: "HUM 205", title: "Texts in Motion", department: "Humanities", credits: "4", crossListed: [] },
  { code: "HUM 302", title: "Gender in Global Perspective", department: "Humanities", credits: "4", crossListed: [] },
  { code: "HUM 405", title: "The Curatorial: Theory and Practice", department: "Humanities", credits: "4", crossListed: ["MEDIART 405"] },
  { code: "HUM 490", title: "Senior Seminar in Humanities", department: "Humanities", credits: "4", crossListed: [] },
  { code: "INFOSCI 102", title: "Computation and Problem Solving", department: "Information Science", credits: "4", crossListed: [] },
  { code: "INFOSCI 103", title: "Computation, Society & Culture", department: "Information Science", credits: "4", crossListed: [] },
  { code: "INFOSCI 104", title: "Digital Design", department: "Information Science", credits: "4", crossListed: ["MEDIA 104"] },
  { code: "INFOSCI 105", title: "Experimental Interface Design", department: "Information Science", credits: "4", crossListed: [] },
  { code: "INFOSCI 113", title: "Googlization of Knowledge: Information, Ethics, and Technology", department: "Information Science", credits: "4", crossListed: [] },
  { code: "INFOSCI 201", title: "Interaction & Physical Computing", department: "Information Science", credits: "4", crossListed: [] },
  { code: "INFOSCI 202", title: "3D Modeling and Animation", department: "Information Science", credits: "4", crossListed: [] },
  { code: "INFOSCI 206", title: "Urban Data Visualization and Communication Methods", department: "Information Science", credits: "2", crossListed: [] },
  { code: "INFOSCI 301", title: "Data Visualization and Information Aesthetics", department: "Information Science", credits: "4", crossListed: [] },
  { code: "INFOSCI 302", title: "Urban Informatics and Sustainable Design", department: "Information Science", credits: "4", crossListed: [] },
  { code: "INFOSCI 304", title: "Game Engine Programming and Immersive Media", department: "Information Science", credits: "4", crossListed: [] },
  { code: "INFOSCI 308", title: "Data and Visualization", department: "Information Science", credits: "4", crossListed: [] },
  { code: "INFOSCI 309", title: "Speculative and Critical Design", department: "Information Science", credits: "4", crossListed: [] },
  { code: "INTGSCI 205", title: "Scientific Methods and Communication", department: "Integrated Science", credits: "4", crossListed: [] },
  { code: "ITALIAN 25", title: "Advanced Intermediate Italian", department: "Italian", credits: "4", crossListed: [] },
  { code: "ITALIAN 101", title: "Beginning Italian 1", department: "Italian", credits: "4", crossListed: [] },
  { code: "ITALIAN 102", title: "Beginning Italian 2", department: "Italian", credits: "4", crossListed: [] },
  { code: "JAPANESE 23", title: "Intermediate Japanese", department: "Japanese", credits: "4", crossListed: [] },
  { code: "JAPANESE 101", title: "Beginning Japanese 1", department: "Japanese", credits: "4", crossListed: [] },
  { code: "JAPANESE 102", title: "Beginning Japanese 2", department: "Japanese", credits: "4", crossListed: [] },
  { code: "JAPANESE 201", title: "Intermediate Japanese 1", department: "Japanese", credits: "4", crossListed: [] },
  { code: "JAPANESE 202", title: "Intermediate Japanese 2", department: "Japanese", credits: "4", crossListed: [] },
  { code: "KOREAN 101", title: "Beginning Korean 1", department: "Korean", credits: "4", crossListed: [] },
  { code: "KOREAN 102", title: "Beginning Korean 2", department: "Korean", credits: "4", crossListed: [] },
  { code: "LATIN 25", title: "Introduction to Literature", department: "Latin", credits: "4", crossListed: [] },
  { code: "LIT 105", title: "The Epic of America (the novel)", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 106", title: "American Otherness and Otherness in America", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 107", title: "From Data to Narrative: A Workshop in Non-fiction Writing", department: "Literature", credits: "2", crossListed: [] },
  { code: "LIT 108", title: "Love and Dreams on the Chinese Stage", department: "Literature", credits: "2", crossListed: ["MEDIART 108"] },
  { code: "LIT 109", title: "Writing Stories for Children", department: "Literature", credits: "2", crossListed: [] },
  { code: "LIT 110", title: "The Art of the Interview", department: "Literature", credits: "2", crossListed: [] },
  { code: "LIT 111", title: "Crafting Narratives in Video Games", department: "Literature", credits: "2", crossListed: [] },
  { code: "LIT 112", title: "Writing Through Fairytale", department: "Literature", credits: "2", crossListed: [] },
  { code: "LIT 201", title: "Asian-American Arts and Letters", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 202", title: "African American Literature and Culture", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 203", title: "Reading Empire", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 204", title: "Online Novels and the Chinese Public Sphere", department: "Literature", credits: "4", crossListed: ["MEDIA 204"] },
  { code: "LIT 205", title: "American Lyric Across Borders (poetry)", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 208", title: "From Cool Japan to the Korean Wave: Popular Culture from East Asia", department: "Literature", credits: "4", crossListed: ["ARTS 208"] },
  { code: "LIT 209", title: "Critical Inter-Asia: Rethinking Local and Global Connections", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 210", title: "Writing Machines: Literature, Technology, and the Future", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 211", title: "Politics and Literature", department: "Literature", credits: "4", crossListed: ["POLSCI 211"] },
  { code: "LIT 212", title: "Survival of the Fittest: Stories of Endurance and Extinction in World Literature", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 213", title: "Literature and Global Citizenship", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 214", title: "Introduction to Literary Research Writ Large", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 215", title: "Self-Making in the American Imagination", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 216", title: "Introduction to Creative Writing and Translation", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 219", title: "Stage Translation for Kunqu", department: "Literature", credits: "2", crossListed: ["MEDIART 219"] },
  { code: "LIT 220", title: "Line Breaks and Chapbooks: Poetry Workshop", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 221", title: "Comparing Religions: Texts, Orality, and Myth", department: "Literature", credits: "4", crossListed: ["RELIG 221"] },
  { code: "LIT 223", title: "Topics in Modern and Premodern Chinese Literature", department: "Literature", credits: "4", crossListed: ["CHINESE 423"] },
  { code: "LIT 301", title: "The Realist Moment", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 302", title: "America's Novel Modernity", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 303", title: "The Literary Arts of the Cold War", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 307", title: "Digital Storytelling", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 309", title: "What('s) the Fuss? The Art and Power of Banned Literature", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 310", title: "Translating Kunqu for the Global Stage", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 311", title: "Poetry in Conversation", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 312", title: "Writing the World: Travel Narratives and Beyond", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 313", title: "Anatomy of Emotions: Literature and Psychoanalysis", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 314", title: "Big Stories: Fiction and Non-Fiction Workshop", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 315", title: "Translation Theory", department: "Literature", credits: "4", crossListed: [] },
  { code: "LIT 398", title: "Special Topics in World Literature", department: "Literature", credits: "4", crossListed: [] },
  { code: "MATSCI 101", title: "Introduction to Materials", department: "Material Science", credits: "4", crossListed: [] },
  { code: "MATSCI 201", title: "Fundamentals of Materials Science", department: "Material Science", credits: "4", crossListed: [] },
  { code: "MATSCI 202", title: "Mathematical Method for Materials Science", department: "Material Science", credits: "4", crossListed: [] },
  { code: "MATSCI 301", title: "Materials Synthesis and Characterization (Lab)", department: "Material Science", credits: "4", crossListed: [] },
  { code: "MATSCI 302", title: "Electronic, Optical and Magnetic Properties of Materials", department: "Material Science", credits: "4", crossListed: [] },
  { code: "MATSCI 303", title: "Phase Transformations", department: "Material Science", credits: "4", crossListed: [] },
  { code: "MATSCI 401", title: "Mechanical Properties of Materials", department: "Material Science", credits: "4", crossListed: [] },
  { code: "MATSCI 402", title: "Introduction to Nanoscale Functional Materials", department: "Material Science", credits: "4", crossListed: [] },
  { code: "MATSCI 403", title: "Quantum Physics for Materials Science", department: "Material Science", credits: "4", crossListed: [] },
  { code: "MATSCI 404", title: "Polymers and Biomaterials", department: "Material Science", credits: "4", crossListed: [] },
  { code: "MATSCI 405", title: "Bio-Inspired Smart Materials", department: "Material Science", credits: "4", crossListed: [] },
  { code: "MATH 21", title: "Introduction to Calculus I", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 22", title: "Introduction to Calculus II", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 101", title: "Introductory Calculus", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 105", title: "Calculus", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 201", title: "Multivariable Calculus", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 202", title: "Linear Algebra", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 203", title: "Advanced Calculus", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 206", title: "Probability and Statistics", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 301", title: "Advanced Introduction to Probability", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 302", title: "Numerical Analysis", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 303", title: "ODE and Dynamical Systems", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 304", title: "Numerical Analysis and Optimization", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 305", title: "Advanced Linear Algebra", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 306", title: "Number Theory", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 307", title: "Complex Analysis", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 308", title: "Real Analysis", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 317", title: "Quantitative Finance", department: "Mathematics", credits: "4", crossListed: ["ECON 317"] },
  { code: "MATH 401", title: "Abstract Algebra", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 403", title: "Partial Differential Equations", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 404", title: "Stochastic Modeling & Computing", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 405", title: "Mathematics of Data Analysis and Machine Learning", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 406", title: "Mathematical Modeling", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 407", title: "General Relativity", department: "Mathematics", credits: "4", crossListed: ["PHYS 407"] },
  { code: "MATH 408", title: "Differential Geometry", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 409", title: "Topology", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 410", title: "Modeling Biological Systems", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 411", title: "Stochastic Process for Finance", department: "Mathematics", credits: "4", crossListed: ["ECON 411"] },
  { code: "MATH 412", title: "Functional Analysis", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 414", title: "Optimization and Control", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MATH 450", title: "Measure and Integration", department: "Mathematics", credits: "4", crossListed: [] },
  { code: "MEDIA 104", title: "Digital Design", department: "Media", credits: "4", crossListed: ["INFOSCI 104"] },
  { code: "MEDIA 201", title: "New Media and Society", department: "Media", credits: "4", crossListed: ["CULANTH 201"] },
  { code: "MEDIA 202", title: "Culture and Industry", department: "Media", credits: "4", crossListed: ["GCULS 201", "CULANTH 202"] },
  { code: "MEDIA 203", title: "Global Media and Communication", department: "Media", credits: "4", crossListed: [] },
  { code: "MEDIA 204", title: "Online Novels and the Chinese Public Sphere", department: "Media", credits: "4", crossListed: ["LIT 204"] },
  { code: "MEDIA 207", title: "Cultures of New Media", department: "Media", credits: "4", crossListed: ["CULANTH 207"] },
  { code: "MEDIART 101", title: "Introduction to Arts and Media", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 103", title: "Introduction to Moving Image Practice", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 104", title: "Introduction to Photography", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 108", title: "Love and Dreams on the Chinese Stage", department: "Media and Arts", credits: "2", crossListed: ["LIT 108"] },
  { code: "MEDIART 111", title: "Archive", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 112", title: "Race on Film", department: "Media and Arts", credits: "2", crossListed: [] },
  { code: "MEDIART 113", title: "Exploring Music", department: "Media and Arts", credits: "2", crossListed: [] },
  { code: "MEDIART 114", title: "Film Musicals and Musical Films", department: "Media and Arts", credits: "2", crossListed: [] },
  { code: "MEDIART 116", title: "Understanding Film: Technique and Style", department: "Media and Arts", credits: "2", crossListed: [] },
  { code: "MEDIART 117", title: "Studio Drawing and Animation", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 118", title: "Introduction to Dance and Choreography", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 119", title: "Fashion and Gender in China", department: "Media and Arts", credits: "2", crossListed: ["GCULS 119"] },
  { code: "MEDIART 198", title: "Special Topics in Creative Practice", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 202", title: "Creativity and Entrepreneurship", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 205", title: "Digital Imaging and Graphic Design", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 206", title: "Computer Graphics", department: "Media and Arts", credits: "4", crossListed: ["COMPSCI 208"] },
  { code: "MEDIART 207", title: "Elements of Story: Introduction to Narrative Structure", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 208", title: "Chinese Mass Media", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 209", title: "Introduction to Visual Culture", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 210", title: "Arts and Media Practicum", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 211", title: "Media, Arts, and Critical Theory", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 212", title: "Editing the Video Essay", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 213", title: "Web-Based Multimedia Design", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 215", title: "Documenting City Life", department: "Media and Arts", credits: "2", crossListed: [] },
  { code: "MEDIART 219", title: "Stage Translation for Kunqu", department: "Media and Arts", credits: "2", crossListed: ["LIT 219"] },
  { code: "MEDIART 220", title: "Visual Anthropology", department: "Media and Arts", credits: "4", crossListed: ["CULANTH 220"] },
  { code: "MEDIART 221", title: "Introduction to Composition", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 222", title: "Electronic Sound: Sampling and Synthesis", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 223", title: "Shot by Shot: Concept and Frame Composition", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 224", title: "Animation: From Anima to Animae", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 225", title: "Fundamentals of Tonal Music Theory", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 226", title: "Eco-Cinema: China's Environmental and Ecological Crisis", department: "Media and Arts", credits: "4", crossListed: ["GCULS 226"] },
  { code: "MEDIART 301", title: "Experimental Filmmaking", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 303", title: "Documentary Photography and the Cultural Landscape", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 305", title: "Advanced Documentary Practice", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 306", title: "Foundations of Interactive Game Design", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 310", title: "Screenwriting", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 311", title: "Cinematography", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 312", title: "Graphic Design in Motion", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 321", title: "Practices in Digital Humanities", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 322", title: "Installation Art", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 323", title: "Sound Design and Music for Film", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 324", title: "The Photographic Essay", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 401", title: "Campaigns, Marketing, and Persuasion", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MEDIART 405", title: "The Curatorial: Theory and Practice", department: "Media and Arts", credits: "4", crossListed: ["GCULS 405"] },
  { code: "MEDIART 490", title: "Senior Seminar: Advanced Topics", department: "Media and Arts", credits: "4", crossListed: [] },
  { code: "MILITSCI 101", title: "Military Theory", department: "Military Science", credits: "2", crossListed: [] },
  { code: "MILITSCI 102", title: "Military Skills Practice", department: "Military Science", credits: "2", crossListed: [] },
  { code: "NEUROSCI 102", title: "Biological Basis of Behavior", department: "Neuroscience", credits: "4", crossListed: [] },
  { code: "NEUROSCI 202", title: "Medical Neuroscience", department: "Neuroscience", credits: "4", crossListed: [] },
  { code: "NEUROSCI 212", title: "Cognitive Neuroscience", department: "Neuroscience", credits: "4", crossListed: [] },
  { code: "NEUROSCI 301", title: "Research Methods in Neuroscience", department: "Neuroscience", credits: "4", crossListed: [] },
  { code: "NEUROSCI 307", title: "From Action to Emotion: The Role of the Basal Ganglia", department: "Neuroscience", credits: "4", crossListed: [] },
  { code: "PHIL 106", title: "Global Philosophy", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 107", title: "What's the Right Thing to Do? Ethics and Justice in the Modern World", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 108", title: "Philosophy and Ethics of Artificial Intelligence", department: "Philosophy", credits: "2", crossListed: [] },
  { code: "PHIL 109", title: "Philosophy through Computer Science", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 110", title: "Philosophy and Sport", department: "Philosophy", credits: "2", crossListed: [] },
  { code: "PHIL 111", title: "Non-Human Animal Ethics", department: "Philosophy", credits: "2", crossListed: [] },
  { code: "PHIL 112", title: "Thinking and Doing", department: "Philosophy", credits: "2", crossListed: [] },
  { code: "PHIL 113", title: "The Philosophy of Authenticity in 5 Movies", department: "Philosophy", credits: "2", crossListed: [] },
  { code: "PHIL 114", title: "Play, Games, and Sport", department: "Philosophy", credits: "2", crossListed: [] },
  { code: "PHIL 115", title: "Confucianism and Feminism", department: "Philosophy", credits: "2", crossListed: [] },
  { code: "PHIL 205", title: "Logic", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 207", title: "Ethical Theory in Philosophical Traditions", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 208", title: "Ancient Greek and Roman Philosophy", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 209", title: "17th and 18th Century European Philosophy", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 210", title: "Introduction to Western Philosophy", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 226", title: "History of Chinese Philosophy", department: "Philosophy", credits: "4", crossListed: ["HIST 226"] },
  { code: "PHIL 301", title: "Philosophy of Mind", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 302", title: "Philosophy of Language", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 303", title: "Topics in Feminist Philosophy", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 304", title: "Philosophy of Science", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 305", title: "Cross-Cultural Philosophy", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 306", title: "Epistemology", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 307", title: "Metaphysics", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 309", title: "Philosophy of the Social Sciences", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PHIL 398", title: "Special Topics in Philosophy", department: "Philosophy", credits: "4", crossListed: [] },
  { code: "PPE 101", title: "Introduction to Philosophy, Politics, and Economics", department: "Philosophy, Politics and Economics", credits: "4", crossListed: [] },
  { code: "PPE 202", title: "Ethics, Markets, and Politics", department: "Philosophy, Politics and Economics", credits: "4", crossListed: [] },
  { code: "PPE 303", title: "Conceptions of Democracy and Meritocracy", department: "Philosophy, Politics and Economics", credits: "4", crossListed: [] },
  { code: "PPE 490", title: "Senior Seminar in Philosophy, Politics, and Economics", department: "Philosophy, Politics and Economics", credits: "4", crossListed: [] },
  { code: "PHYS 25", title: "Introduction to Mechanics", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 26", title: "Introduction to Electricity and Magnetism", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 101", title: "Frontiers of 21^st^ Century Physics", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 105", title: "The Science of Traditional Asian Music", department: "Physics", credits: "4", crossListed: ["ARTS 105"] },
  { code: "PHYS 121", title: "Integrated Science -- Physics", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 122", title: "General Physics II: Electricity, Magnetism and Light", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 134", title: "Introductory Astronomy", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 201", title: "Optics and Modern Physics", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 301", title: "Classical Mechanics", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 302", title: "Thermal and Statistical Physics", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 303", title: "Introduction to Biophysics", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 304", title: "Electricity and Magnetism", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 305", title: "Machine Learning for Physical Science", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 306", title: "Quantum Mechanics", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 310", title: "Physics of Particulate Materials", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 402", title: "Solid State and Soft Matter Physics", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 403", title: "Introduction to Nuclear and Particle Physics", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 404", title: "Nonlinear Dynamics", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 405", title: "Advanced Physics Laboratory and Seminar", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 406", title: "Advanced Biophysics", department: "Physics", credits: "4", crossListed: [] },
  { code: "PHYS 407", title: "General Relativity", department: "Physics", credits: "4", crossListed: ["MATH 407"] },
  { code: "PHYS 408", title: "Quantum Information Science", department: "Physics", credits: "4", crossListed: [] },
  { code: "POLECON 105", title: "China and the Global South", department: "Political Economy", credits: "2", crossListed: [] },
  { code: "POLECON 201", title: "International Political Economy", department: "Political Economy", credits: "4", crossListed: [] },
  { code: "POLECON 301", title: "International Development", department: "Political Economy", credits: "4", crossListed: [] },
  { code: "POLECON 302", title: "China's Economic Transition", department: "Political Economy", credits: "4", crossListed: ["GCHINA 301"] },
  { code: "POLECON 401", title: "Political Economy of the Chinese Reform", department: "Political Economy", credits: "4", crossListed: ["GCHINA 401"] },
  { code: "POLECON 490", title: "Senior Seminar: Advanced Topics", department: "Political Economy", credits: "4", crossListed: [] },
  { code: "POLSCI 20", title: "American Government and Politics", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 21", title: "Comparative Government and Politics", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 101", title: "International Politics", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 104", title: "Comparative Politics and Institutions", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 105", title: "Contemporary Political Ideologies", department: "Political Science", credits: "2", crossListed: [] },
  { code: "POLSCI 106", title: "Political Rhetoric, Crisis, and Leadership", department: "Political Science", credits: "2", crossListed: [] },
  { code: "POLSCI 108", title: "Introduction to Political Theory", department: "Political Science", credits: "2", crossListed: [] },
  { code: "POLSCI 202", title: "U.S. Citizenship: History, Meaning and Conflict", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 203", title: "Civil Rights and Civil Liberties", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 204", title: "The U.S. Constitution and its Critics", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 205", title: "American Ideas and Global Receptions", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 207", title: "Democratic Institutions in America", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 208", title: "Political and Social Inequality", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 209", title: "Democratic Erosion", department: "Political Science", credits: "2", crossListed: [] },
  { code: "POLSCI 210", title: "International Relations in East Asia", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 211", title: "Politics and Literature", department: "Political Science", credits: "4", crossListed: ["LIT 211"] },
  { code: "POLSCI 212", title: "Pathologies of Modern Society: Foundational Ideas", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 213", title: "Populism", department: "Political Science", credits: "2", crossListed: [] },
  { code: "POLSCI 214", title: "Authoritarianism and the Struggle for Democracy in Latin America", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 215", title: "The Political History of Modern Architecture: From Revolution through Neoliberalism", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 216", title: "War and Peace: Foundations of the International Political Order", department: "Political Science", credits: "2", crossListed: [] },
  { code: "POLSCI 219", title: "The U.S. Legal System: Lawyers, Judges, Lawmakers, & Bureaucrats", department: "Political Science", credits: "4", crossListed: ["PUBPOL 219"] },
  { code: "POLSCI 222", title: "Institutions for Social Choice", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 223", title: "Power and Justice in the History of Political Thought", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 302", title: "Public Opinion", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 303", title: "International Politics of East Asia", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 307", title: "Political Economy of Institutions", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 308", title: "Global Governance", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 309", title: "Networks in a Globalizing World", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 310", title: "America in the World", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 312", title: "Islamic Political Thought", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 313", title: "Political Psychology", department: "Political Science", credits: "4", crossListed: ["PSYCH 313"] },
  { code: "POLSCI 314", title: "Migration, the State, and Refugees", department: "Political Science", credits: "4", crossListed: ["CULANTH 314"] },
  { code: "POLSCI 315", title: "American Politics in Comparative Perspective", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 316", title: "Sino-African relations in History and Present", department: "Political Science", credits: "4", crossListed: [] },
  { code: "POLSCI 317", title: "Politics of Organization", department: "Political Science", credits: "4", crossListed: ["SOSC317"] },
  { code: "PSYCH 101", title: "Introductory Psychology", department: "Psychology", credits: "4", crossListed: [] },
  { code: "PSYCH 110", title: "Mindfulness, Stress, and Health: Eastern and Western Perspectives", department: "Psychology", credits: "2", crossListed: [] },
  { code: "PSYCH 202", title: "Cognitive Psychology", department: "Psychology", credits: "4", crossListed: [] },
  { code: "PSYCH 203", title: "Developmental Psychology", department: "Psychology", credits: "4", crossListed: [] },
  { code: "PSYCH 204", title: "Social Psychology", department: "Psychology", credits: "4", crossListed: [] },
  { code: "PSYCH 205", title: "Abnormal Psychology", department: "Psychology", credits: "4", crossListed: [] },
  { code: "PSYCH 304", title: "Quantitative Research Methods and Statistics for Psychological Science", department: "Psychology", credits: "4", crossListed: [] },
  { code: "PSYCH 313", title: "Political Psychology", department: "Psychology", credits: "4", crossListed: ["POLSCI 313"] },
  { code: "PSYCH 405", title: "Conceptual Issues & Critical Debates in Psychology", department: "Psychology", credits: "4", crossListed: [] },
  { code: "PUBPOL 101", title: "Introduction to Policy Analysis", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 106", title: "Urbanizing China: Spatial and Social Dynamics in Chinese Cities", department: "Public Policy", credits: "2", crossListed: [] },
  { code: "PUBPOL 110", title: "Introduction to Human Rights", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 111", title: "Communicating Climate Solutions: Writing for Impact", department: "Public Policy", credits: "2", crossListed: [] },
  { code: "PUBPOL 201", title: "Climate Change Law and Policy", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 202", title: "Global Disasters: Science and Policy", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 204", title: "Governing Cities", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 205", title: "Microeconomic Policy Tools", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 209", title: "The Politics of Environmental Crises", department: "Public Policy", credits: "2", crossListed: [] },
  { code: "PUBPOL 211", title: "Globalization and Public Policy", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 213", title: "Authoritarian Regimes", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 219", title: "The U.S. Legal System: Lawyers, Judges, Lawmakers, & Bureaucrats", department: "Public Policy", credits: "4", crossListed: ["POLSCI 219"] },
  { code: "PUBPOL 220", title: "Introduction to Regulatory Governance", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 221", title: "Comparative Social Policy", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 222", title: "Technology Policy and Regulation", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 223", title: "Comparative Educational Systems", department: "Public Policy", credits: "4", crossListed: ["SOCIOL 223"] },
  { code: "PUBPOL 301", title: "Political Analysis for Public Policy", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 303", title: "Policy Choice as Value Conflict", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 308", title: "Managing the Oceans to Solve Global Problems", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 311", title: "Economic and Political History of the European Union", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 312", title: "News as Moral Battleground", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 315", title: "Economics of the Public Sector", department: "Public Policy", credits: "4", crossListed: ["ECON 315"] },
  { code: "PUBPOL 316", title: "The Modern Regulatory State", department: "Public Policy", credits: "4", crossListed: ["HIST 316"] },
  { code: "PUBPOL 317", title: "Plastic Planet: Pollution and Solutions", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 318", title: "How to Change the World: The Role of Non-State Actors", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "PUBPOL 401", title: "One Health Policy and Practice", department: "Public Policy", credits: "4", crossListed: [] },
  { code: "RELIG 102", title: "The Historical Jesus", department: "Religious Studies", credits: "4", crossListed: [] },
  { code: "RELIG 106", title: "Religion and Leadership", department: "Religious Studies", credits: "4", crossListed: [] },
  { code: "RELIG 107", title: "Readings in Religious Literature", department: "Religious Studies", credits: "2", crossListed: [] },
  { code: "RELIG 108", title: "History of God in Seven Paintings", department: "Religious Studies", credits: "2", crossListed: [] },
  { code: "RELIG 201", title: "Confucianism, Daoism, Buddhism", department: "Religious Studies", credits: "4", crossListed: [] },
  { code: "RELIG 202", title: "Modern Buddhism", department: "Religious Studies", credits: "4", crossListed: [] },
  { code: "RELIG 203", title: "The History of God", department: "Religious Studies", credits: "4", crossListed: ["HIST 233"] },
  { code: "RELIG 204", title: "The Problem of Evil", department: "Religious Studies", credits: "4", crossListed: [] },
  { code: "RELIG 205", title: "Religion, Power, and Social Change", department: "Religious Studies", credits: "4", crossListed: ["CULSOC 205"] },
  { code: "RELIG 206", title: "Animism, Shamanism, Indigeneity", department: "Religious Studies", credits: "4", crossListed: [] },
  { code: "RELIG 221", title: "Comparing Religions: Texts, Orality, and Myth", department: "Religious Studies", credits: "4", crossListed: ["LIT 221"] },
  { code: "RELIG 302", title: "Chinese Religious and Philosophical Thought on the Environment", department: "Religious Studies", credits: "4", crossListed: [] },
  { code: "RELIG 305", title: "Modern Religion", department: "Religious Studies", credits: "4", crossListed: [] },
  { code: "SOSC 102", title: "Introduction to Research Methods", department: "Social Science", credits: "4", crossListed: [] },
  { code: "SOSC 110", title: "Innovation and Creativity", department: "Social Science", credits: "2", crossListed: [] },
  { code: "SOSC 204", title: "Business Ethics", department: "Social Science", credits: "4", crossListed: [] },
  { code: "SOSC 205", title: "Linear Regression: Introduction to Econometrics", department: "Social Science", credits: "4", crossListed: [] },
  { code: "SOSC 206", title: "Qualitative Research Methods", department: "Social Science", credits: "4", crossListed: [] },
  { code: "SOSC 302", title: "Research Designs for Causal Inference", department: "Social Science", credits: "4", crossListed: [] },
  { code: "SOSC 314", title: "Computational Social Science", department: "Social Science", credits: "4", crossListed: [] },
  { code: "SOSC 315", title: "Urban Sociology", department: "Social Science", credits: "4", crossListed: [] },
  { code: "SOSC 317", title: "Politics of Organization", department: "Social Science", credits: "4", crossListed: ["POLSCI 317"] },
  { code: "SOSC 320", title: "Panel Data: Advanced Econometric Methods", department: "Social Science", credits: "4", crossListed: [] },
  { code: "SOSC 333", title: "Social and Economic Networks", department: "Social Science", credits: "4", crossListed: ["ECON 333"] },
  { code: "SOSC 405", title: "The Future of the City", department: "Social Science", credits: "4", crossListed: [] },
  { code: "SOCIOL 101", title: "Introduction to Sociology", department: "Sociology", credits: "4", crossListed: [] },
  { code: "SOCIOL 104", title: "Love, Marriage, and Family in Comparative Perspective", department: "Sociology", credits: "4", crossListed: [] },
  { code: "SOCIOL 105", title: "Non-Governmental Organizations in China", department: "Sociology", credits: "4", crossListed: [] },
  { code: "SOCIOL 202", title: "Sociology of Culture", department: "Sociology", credits: "4", crossListed: [] },
  { code: "SOCIOL 206", title: "Reshaping Global Urbanization", department: "Sociology", credits: "4", crossListed: [] },
  { code: "SOCIOL 212", title: "Contemporary Social Problems", department: "Sociology", credits: "4", crossListed: [] },
  { code: "SOCIOL 213", title: "Family, Work, and Inequality", department: "Sociology", credits: "4", crossListed: [] },
  { code: "SOCIOL 223", title: "Comparative Educational Systems", department: "Sociology", credits: "4", crossListed: ["PUBPOL 223"] },
  { code: "SOCIOL 305", title: "Theory and Society", department: "Sociology", credits: "4", crossListed: [] },
  { code: "SOCIOL 306", title: "Contemporary Population Problems", department: "Sociology", credits: "4", crossListed: [] },
  { code: "SOCIOL 310", title: "Gender and Society", department: "Sociology", credits: "4", crossListed: [] },
  { code: "SOCIOL 380", title: "History of Environmental Social Movements", department: "Sociology", credits: "4", crossListed: [] },
  { code: "SPANISH 25", title: "Advanced Intermediate Spanish", department: "Spanish", credits: "4", crossListed: [] },
  { code: "SPANISH 101", title: "Beginning Spanish 1", department: "Spanish", credits: "4", crossListed: [] },
  { code: "SPANISH 102", title: "Beginning Spanish 2", department: "Spanish", credits: "4", crossListed: [] },
  { code: "SPANISH 110", title: "Introduction to the World of Spanish", department: "Spanish", credits: "4", crossListed: [] },
  { code: "STATS 101", title: "Introduction to Applied Statistical Methods", department: "Statistics", credits: "4", crossListed: [] },
  { code: "STATS 102", title: "Introduction to Data Science", department: "Statistics", credits: "4", crossListed: [] },
  { code: "STATS 201", title: "Introduction to Machine Learning for Social Science", department: "Statistics", credits: "4", crossListed: [] },
  { code: "STATS 202", title: "Modeling and Predicting", department: "Statistics", credits: "4", crossListed: [] },
  { code: "STATS 210", title: "Probability, Random Variables and Stochastic Processes", department: "Statistics", credits: "4", crossListed: [] },
  { code: "STATS 211", title: "Introduction to Stochastic Processes", department: "Statistics", credits: "4", crossListed: [] },
  { code: "STATS 301", title: "Statistics", department: "Statistics", credits: "4", crossListed: [] },
  { code: "STATS 302", title: "Principles of Machine Learning", department: "Statistics", credits: "4", crossListed: ["COMPSCI 309"] },
  { code: "STATS 303", title: "Statistical Machine Learning", department: "Statistics", credits: "4", crossListed: [] },
  { code: "STATS 304", title: "Bayesian and Modern Statistics", department: "Statistics", credits: "4", crossListed: [] },
  { code: "STATS 401", title: "Data Acquisition and Visualization", department: "Statistics", credits: "4", crossListed: [] },
  { code: "STATS 402", title: "Interdisciplinary Data Analysis", department: "Statistics", credits: "4", crossListed: [] },
  { code: "STATS 403", title: "Deep Learning", department: "Statistics", credits: "4", crossListed: [] },
  { code: "STATS 404", title: "Probabilistic Graphical Models", department: "Statistics", credits: "4", crossListed: [] },
  { code: "WOC 105", title: "Intercultural Adaptation -- Improving Intercultural and Translingual Experiences", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 106", title: "Introducing Suzhou to the World: Oral Communication across Cultural Boundaries", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 107", title: "Reading Suzhou Through Literature and History", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 108", title: "Intercultural Communication", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 110", title: "Should We Care About Endangered Languages", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 111", title: "Generative Artificial Intelligence and Writing", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 112", title: "Writing, Identity, and Social Media in the Digital Age", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 113", title: "Language, Identity, and Intercultural Communication", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 114", title: "Understanding Other Cultures Through Discussion and AI", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 190", title: "Special Topics in Writing", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 201", title: "Academic Writing 1: Argumentation Across Disciplines", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 202", title: "Academic Writing 2: Genre & Structure Across Disciplines", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 205", title: "Writing about Endangered Languages", department: "Written and Oral Communication", credits: "4", crossListed: [] },
  { code: "WOC 206", title: "Debating Scenarios for Sustainable Futures", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 207", title: "Translation Workshop: The Reflection of Meaning", department: "Written and Oral Communication", credits: "2", crossListed: ["CHINESE 408"] },
  { code: "WOC 208", title: "An Introduction to Language Teaching", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 209", title: "Intercultural Communication and Advertising -- Persuasion Across Cultures", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 210", title: "Translation Workshop: Adaptation and Transformation (Chinese-English; English-Chinese)", department: "Written and Oral Communication", credits: "2", crossListed: ["CHINESE 416"] },
  { code: "WOC 211", title: "Composing Research 1: Developing a Research Proposal", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 212", title: "Composing Research 2: Developing a Research Paper", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 213", title: "From Text to World: Editing and Publishing", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 214", title: "Reading Chinese Love Stories in Novels and Memoirs", department: "Written and Oral Communication", credits: "2", crossListed: ["CHINESE 414"] },
  { code: "WOC 215", title: "Watching Forbidden Love in Chinese Films", department: "Written and Oral Communication", credits: "2", crossListed: ["CHINESE 415"] },
  { code: "WOC 216", title: "Introduction to Feature Writing and International Reporting", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 217", title: "Introduction to News Writing", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 218", title: "Public Speaking", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 219", title: "Travelling Texts, Moving Images: East Meets West in Film Remakes", department: "Written and Oral Communication", credits: "2", crossListed: ["CHINESE 419"] },
  { code: "WOC 221", title: "Investigating Forensic Science: Skills and Techniques for Scientific Writing", department: "Written and Oral Communication", credits: "2", crossListed: [] },
  { code: "WOC 222", title: "Martial Arts Cinema: Nation, Gender, and Identity", department: "Written and Oral Communication", credits: "2", crossListed: ["CHINESE 422"] },
  { code: "WOC 290", title: "Special Topics in Written and Oral Communication", department: "Written and Oral Communication", credits: "4", crossListed: [] },
];
