-- Dozens of new dashboard widget kinds (see the Trello "Widget idea backlog" card),
-- plus a per-day visit log that powers the login-streak and admin active-users widgets.

-- AlterEnum
ALTER TYPE "WidgetKind" ADD VALUE 'EVENTS_NEXT_RSVP';
ALTER TYPE "WidgetKind" ADD VALUE 'EVENTS_MY_WEEK';
ALTER TYPE "WidgetKind" ADD VALUE 'EVENTS_HOST_LAUNCH';
ALTER TYPE "WidgetKind" ADD VALUE 'EVENTS_TRENDING';
ALTER TYPE "WidgetKind" ADD VALUE 'EVENTS_HOSTING';
ALTER TYPE "WidgetKind" ADD VALUE 'EVENTS_HAPPENING_NOW';
ALTER TYPE "WidgetKind" ADD VALUE 'EVENTS_DEADLINE';
ALTER TYPE "WidgetKind" ADD VALUE 'SLB_LATEST';
ALTER TYPE "WidgetKind" ADD VALUE 'SLB_POLL';
ALTER TYPE "WidgetKind" ADD VALUE 'SLB_TRENDING';
ALTER TYPE "WidgetKind" ADD VALUE 'LILYPAD_HEADLINE';
ALTER TYPE "WidgetKind" ADD VALUE 'LILYPAD_TICKER';
ALTER TYPE "WidgetKind" ADD VALUE 'WISDOM_TOP';
ALTER TYPE "WidgetKind" ADD VALUE 'WISDOM_TALLY';
ALTER TYPE "WidgetKind" ADD VALUE 'WISDOM_SURPRISE';
ALTER TYPE "WidgetKind" ADD VALUE 'WISDOM_DAILY';
ALTER TYPE "WidgetKind" ADD VALUE 'WISDOM_NEWEST';
ALTER TYPE "WidgetKind" ADD VALUE 'WISDOM_UPVOTES';
ALTER TYPE "WidgetKind" ADD VALUE 'WISDOM_SHARE';
ALTER TYPE "WidgetKind" ADD VALUE 'CLUBS_SPOTLIGHT';
ALTER TYPE "WidgetKind" ADD VALUE 'CLUBS_MINE';
ALTER TYPE "WidgetKind" ADD VALUE 'CLUBS_NEWEST';
ALTER TYPE "WidgetKind" ADD VALUE 'EATS_RANDOM';
ALTER TYPE "WidgetKind" ADD VALUE 'EATS_BUSY';
ALTER TYPE "WidgetKind" ADD VALUE 'EATS_LAST_ORDER';
ALTER TYPE "WidgetKind" ADD VALUE 'CHAT_COMPOSER';
ALTER TYPE "WidgetKind" ADD VALUE 'CHAT_PINNED';
ALTER TYPE "WidgetKind" ADD VALUE 'CHAT_INVITES';
ALTER TYPE "WidgetKind" ADD VALUE 'CHAT_DM';
ALTER TYPE "WidgetKind" ADD VALUE 'DEAR_LATEST';
ALTER TYPE "WidgetKind" ADD VALUE 'DEAR_COMMENTED';
ALTER TYPE "WidgetKind" ADD VALUE 'DEAR_WRITE';
ALTER TYPE "WidgetKind" ADD VALUE 'DEAR_RANDOM';
ALTER TYPE "WidgetKind" ADD VALUE 'COURSES_COMMENTS';
ALTER TYPE "WidgetKind" ADD VALUE 'COURSES_SEARCH';
ALTER TYPE "WidgetKind" ADD VALUE 'COURSES_RESOURCES';
ALTER TYPE "WidgetKind" ADD VALUE 'PROFESSORS_SPOTLIGHT';
ALTER TYPE "WidgetKind" ADD VALUE 'PROFESSORS_REVIEWS';
ALTER TYPE "WidgetKind" ADD VALUE 'PROFESSORS_TO_RATE';
ALTER TYPE "WidgetKind" ADD VALUE 'PLANNER_CREDITS';
ALTER TYPE "WidgetKind" ADD VALUE 'PLANNER_SEMESTERS';
ALTER TYPE "WidgetKind" ADD VALUE 'PROFILE_POINTS';
ALTER TYPE "WidgetKind" ADD VALUE 'PROFILE_ACHIEVEMENTS';
ALTER TYPE "WidgetKind" ADD VALUE 'PROFILE_LEADERBOARD';
ALTER TYPE "WidgetKind" ADD VALUE 'PROFILE_NEXT_ACHIEVEMENT';
ALTER TYPE "WidgetKind" ADD VALUE 'PROFILE_RECENT_POINTS';
ALTER TYPE "WidgetKind" ADD VALUE 'PROFILE_SHOWCASE';
ALTER TYPE "WidgetKind" ADD VALUE 'PROFILE_RECAP';
ALTER TYPE "WidgetKind" ADD VALUE 'CAMPUS_QUICK_LINKS';
ALTER TYPE "WidgetKind" ADD VALUE 'CAMPUS_BREAK_COUNTDOWN';
ALTER TYPE "WidgetKind" ADD VALUE 'CAMPUS_SEMESTER_PROGRESS';
ALTER TYPE "WidgetKind" ADD VALUE 'CAMPUS_DUAL_CLOCK';
ALTER TYPE "WidgetKind" ADD VALUE 'CAMPUS_WEATHER';
ALTER TYPE "WidgetKind" ADD VALUE 'CAMPUS_AIR_QUALITY';
ALTER TYPE "WidgetKind" ADD VALUE 'CAMPUS_LOGIN_STREAK';
ALTER TYPE "WidgetKind" ADD VALUE 'CAMPUS_CURRENCY';
ALTER TYPE "WidgetKind" ADD VALUE 'CAMPUS_CONTACTS';
ALTER TYPE "WidgetKind" ADD VALUE 'MARKET_POST_LAUNCH';
ALTER TYPE "WidgetKind" ADD VALUE 'ADMIN_ACTIVE_USERS';

-- CreateTable
CREATE TABLE "daily_visits" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "day" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "daily_visits_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "daily_visits_day_idx" ON "daily_visits"("day");

-- CreateIndex
CREATE UNIQUE INDEX "daily_visits_userId_day_key" ON "daily_visits"("userId", "day");

-- AddForeignKey
ALTER TABLE "daily_visits" ADD CONSTRAINT "daily_visits_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
